[window] 
dimensions = { columns = 100, lines = 30 } 
padding = { x = 5, y = 5 } 
dynamic_padding = true 
decorations = "full" 
startup_mode = "Windowed" 
dynamic_title = true

[scrolling] 
history = 10000 
multiplier = 3

[font] 
normal = { family = "CaskaydiaCove Nerd Font", style = "Regular" } 
bold = { family = "CaskaydiaCove Nerd Font", style = "Bold" } 
italic = { family = "CaskaydiaCove Nerd Font", style = "Italic" } 
bold_italic = { family = "CaskaydiaCove Nerd Font", style = "Bold Italic" } 
size = 12.0

[colors] 
draw_bold_text_with_bright_colors = true

[colors.primary] 
background = "#1a1b26" 
foreground = "#c0caf5"

[colors.normal] 
black = "#15161e" 
red = "#f7768e" 
green = "#9ece6a" 
yellow = "#e0af68" 
blue = "#7aa2f7" 
magenta = "#bb9af7" 
cyan = "#7dcfff" 
white = "#a9b1d6"

[colors.bright] 
black = "#414868" 
red = "#f7768e" 
green = "#9ece6a" 
yellow = "#e0af68" 
blue = "#7aa2f7" 
magenta = "#bb9af7" 
cyan = "#7dcfff" 
white = "#c0caf5"

[cursor] 
style = { shape = "Block", blinking = "On" } 
blink_interval = 750 
unfocused_hollow = true

[[keyboard.bindings]] 
key = "V" 
mods = "Control|Shift" 
action = "Paste"

[[keyboard.bindings]] 
key = "C" 
mods = "Control|Shift" 
action = "Copy"
